models:
  - model: meta-llama/Llama-3.2-3B-Instruct
  - model: wasifis/llama-bank-assistant
    parameters:
      density: 0.5
      weight: 0.5
  - model: deepsource/Narada-3.2-3B-v1
    parameters:
      density: 0.5
      weight: 0.3
merge_method: ties
base_model: meta-llama/Llama-3.2-3B-Instruct
parameters:
  normalize: true
dtype: float16